backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/podcast
public_folder: /podcast

collections:
  - name: "podcast"
    label: "Podcast"
    folder: "src/pages/podcast"
    create: true
    slug: "{{slug}}-{{year}}-{{month}}-{{day}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "podcast-episode"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Audio file", name: "audiofile", widget: file}
